spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/santander_db
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multpart:
      max-file-size: 50MB
      max-request-size: 50MB

  spring:
    redis:
      host: redis
      port: 6379